Lily 0.1
nurlailifajriyah/todolist pull request #6
Opened 2019-12-31 13:40 UTC by nurlailifajriyah

2019-12-31 14:35 UTC, raidnav commented on app.py
> +    return dumps(collection.find_one({"seq": index}))
refactor this ugly function

2019-12-31 14:36 UTC, pandiwaw requested changes

2019-12-31 14:36 UTC, raidnav commented on app.py
> +        return json.JSONEncoder.default(self, o)
not used, deleted.

2020-01-01 03:06 UTC, raidnav commented
Don't forget to update README.md

2020-01-01 10:12 UTC, nurlailifajriyah commented on app.py
> +        return json.JSONEncoder.default(self, o)
done

2020-01-01 10:13 UTC, nurlailifajriyah commented on app.py
> +    return dumps(collection.find_one({"seq": index}))
done

2020-01-01 10:13 UTC, pandiwaw approved these changes

2020-01-01 10:14 UTC, merged